import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-right"
          expand

          toastOptions={{
            className: "rounded-xl shadow-lg",
            classNames: {
              success: "bg-green-50 text-green-700 border border-green-200",
              error: "bg-red-50 text-red-700 border border-red-200",
              warning: "bg-yellow-50 text-yellow-800 border border-yellow-200",
            },
          }}
        />
      </body>
    </html>
  );
}
